[package]
name = "lagoon_interpreter"
version = "0.1.0"
edition = "2018"

[dependencies]
lagoon_parser = { path = "../lagoon-parser" }
thiserror = "1.0"
colored = "2"
hashbrown = "0.11.2"
bigdecimal = "0.3"